version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=Bake_cake.settings
    command: /app/start.sh