# Generated by Django 4.1.5 on 2024-08-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ягоды')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название торта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='cakes', verbose_name='Изображение торта')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Декор')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Число уровней')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Форма')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Топпинг')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=200, verbose_name='Надпись на торте')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('berries', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.berries')),
                ('decor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.decor')),
                ('level', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.level')),
                ('shape', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.shape')),
                ('topping', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg_bot.topping')),
            ],
        ),
    ]
