# Generated by Django 4.1.5 on 2024-08-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_linkclick_alter_cake_berries_alter_cake_decor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berries',
            options={'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name_plural': 'Форма'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Топпинги'},
        ),
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.AddField(
            model_name='cake',
            name='end_price',
            field=models.FloatField(default=0.0, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cakes', verbose_name='Изображение торта'),
        ),
        migrations.AddField(
            model_name='cake',
            name='ready_to_order',
            field=models.BooleanField(default=False),
        ),
    ]
