# Generated by Django 4.1.5 on 2024-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_linkclick_alter_cake_berries_alter_cake_decor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('telegram_id', models.CharField(max_length=50, verbose_name='телеграмм ID')),
                ('address', models.TextField(verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='berries',
            options={'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name_plural': 'Форма'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Топпинги'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cakes', verbose_name='Изображение торта'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название торта'),
        ),
    ]
