# Generated by Django 4.1.5 on 2024-08-21 14:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_alter_berries_options_alter_cake_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True, verbose_name='Телеграм ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('delivery_time', models.IntegerField(default=3, verbose_name='Срок испольнения заказа')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('comments', models.TextField(max_length=200, verbose_name='Комментарии')),
                ('status', models.TextField(max_length=30, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'verbose_name': 'Декор', 'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Форма'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'Топпинг', 'verbose_name_plural': 'Топпинги'},
        ),
        migrations.AddField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_bot.cake', verbose_name='Заказанный торт'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tg_bot.client', verbose_name='Заказчик'),
        ),
    ]
