# Generated by Django 4.1.5 on 2024-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_alter_cake_berries_alter_cake_decor_alter_cake_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание торта'),
        ),
    ]
