# Generated by Django 4.1.5 on 2024-08-24 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_alter_client_options_remove_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.IntegerField(default=3, verbose_name='Срок исполнения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under', 'на рассмотрении'), ('todo', 'принять в работу'), ('true', 'подтвержден'), ('topay', 'выставить счет'), ('false', 'отменен'), ('delay', 'задерживается')], default='under', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
