# Generated by Django 4.1.5 on 2024-08-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_alter_order_created_at_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='production_time',
        ),
    ]
