# Generated by Django 4.1.5 on 2024-08-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_rename_delivery_date_order_production_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under', 'на рассмотрении'), ('todo', 'принят в работу'), ('true', 'подтвержден'), ('topay', 'выставить счет'), ('false', 'отменен'), ('delay', 'задерживается')], default='under', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
